### ISSUE TITLE
New slurm process executor

### ISSUE THREAD

**Issue by tristan0x** [tristan0x/hpcbench#140]
Here is an example of usage of the new tag definition mechanism based on slurm constraints:

```yaml
network:
  tags:
    uc1:
      nodes: [ n1 ]
    uc2:
      nodes: [ n2 ]
    uc3:
      nodes: [ n3 ]
    uc4:
      nodes: [ n4 ]
    uc5:
      tags: [uc1, uc2, uc3, uc4]
      constraint: "uc1|uc2|uc3|uc4"
    uc5-sample:
      constraint: "[uc1*6&uc2*6]"
    bla:  # this tais is simply an alias
      tags: uc5-sample
    skylake:
      tags: [uc2, uc3, uc4]
      # if number of tags > 1, then NO tag with constraint is allowed

process:
  type: slurm
  config:
    tag_constraint: true
    account: account
    mail-user: no-reply@acme.org
    mail-type: ALL
    srun:
      mpi: pmi2
  environment:
    PLEASE_DO_NOT_DIE: true

benchmarks:
  uc5:
    minimal-tests:
      slurm:
        tag_constraint: false
        account:
        mail-type: FAIL
        nodes: 4096
      type: hpl
```

**Comment by ohm314** [comment]
I"ll start working on the process executor, not sure I will put everything into one MR. maybe the tag constraints can be factored out

**Comment by ohm314** [comment]
The `srun` option should be supported in `command` now, which shall support in the future also the commands for sbatch / salloc:

```yaml
process:
  type: slurm
  config:
    tag_constraint: true
    account: account
    mail-user: no-reply@acme.org
    mail-type: ALL
    command: srun
    srun:
      mpi: pmi2
  environment:
    PLEASE_DO_NOT_DIE: true
```

so, `tag_constraint` and `command` are the only two options, which are not passed to the slurm command. (should we maybe change the syntax a bit to not have a growing list of exceptions?)

**Comment by ohm314** [comment]
I was also thinking about that, maybe that's best, otherwise we will have to keep messing with these options every few commits..

```yaml
process:
  type: slurm
  command: /opt/slurm/bin/srun
  tag_constraint: true
  srun:
    mpi: pmi2
  args:
    account: account
    mail-user: no-reply@acme.org
    mail-type: ALL
  environment:
    PLEASE_DO_NOT_DIE: true
```

**Comment by ohm314** [comment]
next iteration:

```yaml
network:
  tags:
    uc1:
      nodes: [ n1 ]
    uc2:
      nodes: [ n2 ]
    uc3:
      nodes: [ n3 ]
    uc4:
      nodes: [ n4 ]
    uc5:
      tags: [uc1, uc2, uc3, uc4]
    uc5-sample:
      constraint: "[uc1*6&uc2*6]"
    bla:  # this tais is simply an alias
      tags: uc5-sample # a tag can contain one string denoting the aliased tag
    skylake:
      tags: [uc2, uc3, uc4]
      # if number of tags > 1, then NO tag with constraint is allowed

process:
  type: slurm
  commands: 
    sbatch: /opt/slurm/bin/sbatch
    srun: mysrun
  srun:
    mpi: pmi2
    mem-per-cpu: 16g
  sbatch:
    account: account
    mail-user: no-reply@acme.org
    mail-type: ALL

benchmarks:
  uc5:
    minimal-tests:
      srun:
        nodes: 4096
        tasks-per-node: 16
        mpi: hydra
        mem-per-cpu:
      type: hpl

```
- one ben-sh is executed, it checks if it is in "slurm mode". if yes, generate one sbatch per tag. 
- The sbatch will contain one ben-sh command (maybe with indicator argument for tag and the fact that it is inside an sbatch)
- every ben-sh is independent and will generate its own report directory (with slurm jobid in name)
- the final report can be then merged with ben-merge
- srun inside benchmark does not use (and overwrite in config) sbatch options but only cares about srun specific changes (no messing with constraints).
- maybe ben-merge can be run in a dependent sbatch after all the other sbatches are done.
