### ISSUE TITLE
osu doesn't support campaign file argument overrides

### ISSUE THREAD

**Issue by ohm314** [tristan0x/hpcbench#226]

**Comment by tristan0x** [comment]
You can already provide such configuration:

```yaml
benchmarks:
  \*:
    test:
     type:osu
     arguments:
       categories: [osu_bw, osu_latency]
       arguments:
         osu_bw: [-x, 200, -i, 100]
         osu_latency: [-x, 200, -i, 400]
```

Here are my improvements suggestions for the `arguments` argument:
* rename it to `options`
* allow partial override i.e user should have to specify options of all categories when he only wants to customize one.
* if value is a list instead of a dict, then it is used for all categories

Do you see other things @ohm314 ?
