### ISSUE TITLE
Declare network tags from other tags

### ISSUE THREAD

**Issue by tristan0x** [tristan0x/hpcbench#85]
It would be useful to specify tags from other tags, for instance the `skylake` one below:
```yaml
network:
  tags:
    uc1:
      nodes: [node01, node02]
    uc2:
      nodes: [node03, node04]
    uc3:
      nodes: [node05, node06]
    skylake:
      tags: [uc1, uc2]
```

Recursive definition should be detected and properly reported to the user.
